import Head from 'next/head';
import Navbar from '../components/Navbar';
import GlobalStyles from '../styles/globalStyles';
export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
      <Navbar />
    </>
  );
}
