import Head from 'next/head'
import Navbar from "./components/Navbar"
import GlobalStyles from "./components/styles/Global"

export default function Home() {

  return (
    <>
    <GlobalStyles />
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300&display=swap" rel="stylesheet"/>
      </Head>

      <Navbar />
      </>
  )
}
